pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-web:${BUILD_NUMBER} .'
            }
        }

        stage('Test') {
            steps {
                sh 'docker run --rm devops-web:${BUILD_NUMBER} nginx -t'
            }
        }

        stage('Push to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region ap-south-1 |
                docker login --username AWS --password-stdin \
                YOUR_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com

                docker tag devops-web:${BUILD_NUMBER} \
                YOUR_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/devops-web:${BUILD_NUMBER}

                docker push \
                YOUR_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/devops-web:${BUILD_NUMBER}
                '''
            }
        }

        stage('Deploy') {
            steps {
                sh 'kubectl apply -f kubernetes/'
            }
        }
    }
}
